name: cd

on: [push, pull_request, workflow_dispatch]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v3
        with:
          version: 8.x.x

      - name: Install dependencies
        run: pnpm --version && pnpm i

      - name: Build
        run: VITE_BASE_URL="/PhotoEditor/" pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
